swagger: '2.0'
info:
  version: "1.0"
  title: 'IMN ADAPTER - Offer Importation Process Manager Actor'


basePath: /OfferImportationProcessManager
x-beezup-ops:
  repo: IMN
  appRoot: TBD
  apiName: TBD
  namespace: IMN.ADPT.OfferIMP.PM
  comment: |
    Actor


paths:

  '/enabled':
    post:
      summary: When the offer importation is enabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceOfferImportationEnabled'
      responses:
        204:
          description: OK

  '/started':
    post:
      summary: When the offer importation is started
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_importation-events/1.0#/definitions/offerImportationStarted'
      responses:
        204:
          description: OK

  '/completed':
    post:
      summary: When the offer importation is completed
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/offer_importation-events/1.0#/definitions/offerImportationCompleted'
      responses:
        204:
          description: OK


  '/disabled':
    post:
      summary: When the offer importation is disabled
      parameters: 
      - name: request
        in: body
        schema:
          $ref: 'https://api.swaggerhub.com/domains/IMN/merchant-events/1.0#/definitions/merchantMarketplaceOfferImportationDisabled'
      responses:
        204:
          description: OK

definitions:

  x-applies:
    type: object
    properties:
      offerImportationStarted:
        $ref: 'https://api.swaggerhub.com/domains/IMN/offer_importation-events/1.0#/definitions/offerImportationStarted'